/**
 * Tests for src/lib/password.ts
 * Verifies the bcrypt-based password hashing + verification utilities.
 */
import { describe, it, expect } from "vitest";
import {
  hashPassword,
  verifyPassword,
  generateTempPassword,
  validatePasswordStrength,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
} from "@/lib/password";

describe("lib/password", () => {
  describe("hashPassword", () => {
    it("returns a 60-char bcrypt hash starting with $2", () => {
      const hash = hashPassword("myPassword123");
      expect(hash).toMatch(/^\$2[aby]\$/);
      expect(hash.length).toBe(60);
    });

    it("produces different hashes for the same password (bcrypt salts automatically)", () => {
      const h1 = hashPassword("samePassword");
      const h2 = hashPassword("samePassword");
      expect(h1).not.toBe(h2);
    });

    it("throws on empty password", () => {
      expect(() => hashPassword("")).toThrow();
    });

    it("throws on null/undefined", () => {
      expect(() => hashPassword(null as any)).toThrow();
      expect(() => hashPassword(undefined as any)).toThrow();
    });

    it("throws on passwords > 200 chars", () => {
      const long = "a".repeat(201);
      expect(() => hashPassword(long)).toThrow();
    });

    it("accepts passwords up to 200 chars", () => {
      const long = "a".repeat(200);
      const hash = hashPassword(long);
      expect(hash.length).toBe(60);
    });
  });

  describe("verifyPassword", () => {
    it("returns true for a correct password", () => {
      const hash = hashPassword("correctPassword");
      expect(verifyPassword("correctPassword", hash)).toBe(true);
    });

    it("returns false for a wrong password", () => {
      const hash = hashPassword("correctPassword");
      expect(verifyPassword("wrongPassword", hash)).toBe(false);
    });

    it("returns false for null/undefined hash", () => {
      expect(verifyPassword("anything", null)).toBe(false);
      expect(verifyPassword("anything", undefined)).toBe(false);
    });

    it("returns false for null/undefined password", () => {
      const hash = hashPassword("somePassword");
      expect(verifyPassword(null as any, hash)).toBe(false);
      expect(verifyPassword(undefined as any, hash)).toBe(false);
    });

    it("returns false for malformed hash (not a bcrypt hash)", () => {
      expect(verifyPassword("password", "not-a-hash")).toBe(false);
      expect(verifyPassword("password", "$2b$10$short")).toBe(false);
      expect(verifyPassword("password", "")).toBe(false);
    });

    it("returns false for a hash with wrong prefix", () => {
      // Valid length but wrong prefix
      const fakeHash = "$3a$10$" + "a".repeat(53);
      expect(verifyPassword("password", fakeHash)).toBe(false);
    });

    it("verifies hashes generated by Python's bcrypt (cross-language compatibility)", () => {
      // Hash generated externally with: bcrypt.hashpw(b"coffee123", bcrypt.gensalt(10))
      const pythonHash = "$2b$10$DhD/JzLpP8DdILMoCSjiCO2jy8x7d4ulPP0zKlC0Pyy.5Z14GW0qC";
      // This hash is for "coffee123" — verify it works
      expect(verifyPassword("coffee123", pythonHash)).toBe(true);
      expect(verifyPassword("wrong", pythonHash)).toBe(false);
    });
  });

  describe("generateTempPassword", () => {
    it("returns a string of the requested length", () => {
      const pwd = generateTempPassword(16);
      expect(typeof pwd).toBe("string");
      expect(pwd.length).toBe(16);
    });

    it("uses default length of 16", () => {
      const pwd = generateTempPassword();
      expect(pwd.length).toBe(16);
    });

    it("produces different passwords on subsequent calls (randomness)", () => {
      const p1 = generateTempPassword();
      const p2 = generateTempPassword();
      const p3 = generateTempPassword();
      // Extremely unlikely all three are equal
      expect(p1 === p2 && p2 === p3).toBe(false);
    });

    it("only uses safe charset (no ambiguous chars like 0/O/l/1)", () => {
      const pwd = generateTempPassword(100);
      // Should not contain 0, O, l, I, 1 (ambiguous)
      expect(pwd).not.toMatch(/[0OlI1]/);
    });
  });

  describe("validatePasswordStrength", () => {
    it("returns null for a strong password", () => {
      expect(validatePasswordStrength("strongPass123")).toBeNull();
      expect(validatePasswordStrength("Abcdefghij1")).toBeNull();
    });

    it("returns error for password < 8 chars", () => {
      expect(validatePasswordStrength("Ab1")).toBe("Password must be at least 8 characters");
      expect(validatePasswordStrength("Ab1defg")).toBe("Password must be at least 8 characters");
    });

    it("returns null for exactly 8 chars with letter + digit", () => {
      expect(validatePasswordStrength("Abcdefg1")).toBeNull();
    });

    it("returns error for password with no digits", () => {
      expect(validatePasswordStrength("abcdefgh")).toBe("Password must contain at least one digit");
    });

    it("returns error for password with no letters", () => {
      expect(validatePasswordStrength("12345678")).toBe("Password must contain at least one letter");
    });

    it("returns error for empty password", () => {
      expect(validatePasswordStrength("")).toBe("Password must be at least 8 characters");
    });

    it("returns error for null/undefined", () => {
      expect(validatePasswordStrength(null as any)).toBe("Password must be at least 8 characters");
      expect(validatePasswordStrength(undefined as any)).toBe("Password must be at least 8 characters");
    });
  });

  describe("constants", () => {
    it("exports MIN_PASSWORD_LENGTH = 1", () => {
      expect(MIN_PASSWORD_LENGTH).toBe(1);
    });

    it("exports MAX_PASSWORD_LENGTH = 200", () => {
      expect(MAX_PASSWORD_LENGTH).toBe(200);
    });
  });
});
