/**
 * POST /api/admin/operators/[id]/reset-password
 *
 * Admin-initiated password reset. Sets a new bcrypt hash on the operator.
 * The admin chooses the new password (or generates one) and communicates
 * it to the operator out-of-band.
 *
 * Body: {
 *   newPassword?: string,   (optional — if omitted, a random 16-char password is generated and returned)
 * }
 *
 * Response: { ok: true, operatorId, generatedPassword? }
 *           | { ok: false, error }
 *
 * Security notes:
 *   - The new password is hashed with bcrypt before storage
 *   - If admin provides newPassword, it must pass the strength check
 *   - If admin omits newPassword, a random one is generated and RETURNED
 *     in the response (this is the only time it's visible — the admin must
 *     communicate it to the operator immediately)
 *   - The previous password becomes invalid immediately
 */

import { NextRequest, NextResponse } from "next/server";
import { getWritableDb } from "@/lib/db";
import { requireAdmin } from "@/lib/auth";
import {
  hashPassword,
  generateTempPassword,
  validatePasswordStrength,
} from "@/lib/password";
import { writeAuditLog } from "@/lib/audit";
import { revokeAllSessionsForOperator } from "@/lib/sessions";

function nowISO(): string {
  return new Date().toISOString().replace("Z", "+03:00");
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const auth = requireAdmin(request);
  if ("error" in auth) return auth.error;

  try {
    const { id: operatorId } = await params;

    // ─── Parse body (optional — may be empty) ───
    let body: any = {};
    try {
      body = await request.json();
    } catch {
      // Empty body is OK — we'll generate a random password
    }

    const { newPassword } = body;

    // ─── Determine the password to set ───
    let password: string;
    let wasGenerated: boolean;
    if (newPassword !== undefined && newPassword !== null) {
      // Admin provided a password — validate it
      if (typeof newPassword !== "string") {
        return NextResponse.json(
          { ok: false, error: "newPassword must be a string" },
          { status: 400 }
        );
      }
      const strengthError = validatePasswordStrength(newPassword);
      if (strengthError) {
        return NextResponse.json({ ok: false, error: strengthError }, { status: 400 });
      }
      password = newPassword;
      wasGenerated = false;
    } else {
      // Generate a random temp password
      password = generateTempPassword(16);
      wasGenerated = true;
    }

    const db = getWritableDb();
    try {
      // ─── Check the operator exists ───
      const existing = db.prepare(`
        SELECT operator_id FROM operators WHERE operator_id = ?
      `).get(operatorId) as { operator_id: string } | undefined;

      if (!existing) {
        return NextResponse.json({ ok: false, error: "Operator not found" }, { status: 404 });
      }

      // ─── Hash + update ───
      // Set must_change_password=1 only when the password was auto-generated
      // (the user needs to receive it out-of-band and change it on first login).
      // If the admin provided the password themselves, they presumably communicated
      // it deliberately, so we don't force a change.
      const passwordHash = hashPassword(password);
      const mustChange = wasGenerated ? 1 : 0;
      db.prepare(`
        UPDATE operators SET password_hash = ?, must_change_password = ?, updated_ts = ? WHERE operator_id = ?
      `).run(passwordHash, mustChange, nowISO(), operatorId);

      // ─── Revoke all active sessions (forces re-login with new password) ───
      revokeAllSessionsForOperator(operatorId, `admin (${auth.user.email}) — password reset`);

      // ─── Audit log ───
      writeAuditLog({
        actorEmail: auth.user.email,
        actorIp: request.headers.get("x-forwarded-for")?.split(",")[0].trim() || null,
        action: "operator.reset_password",
        targetType: "operator",
        targetId: operatorId,
        details: { autoGenerated: wasGenerated, forcedPasswordChange: wasGenerated },
      });

      return NextResponse.json({
        ok: true,
        operatorId,
        mustChangePassword: wasGenerated,
        // Only return the plaintext password if we generated it — the admin
        // already knows the one they provided.
        ...(wasGenerated ? { generatedPassword: password } : {}),
      });
    } finally {
      db.close();
    }
  } catch (error: any) {
    console.error("[/api/admin/operators/[id]/reset-password] Error:", error);
    return NextResponse.json(
      { ok: false, error: "Failed to reset password — please try again" },
      { status: 500 }
    );
  }
}
