"""
Event types — all event constants for the coffee export system.

Every event published by any agent uses one of these types. This ensures
type safety (no typos) and makes it easy to search for all producers/
consumers of a given event.

Event naming convention: DOMAIN_ACTION (e.g., LEAD_CREATED, SAMPLE_DISPATCHED)
"""

from __future__ import annotations

# ── Lead events ──
LEAD_CREATED = "LEAD_CREATED"
LEAD_ENRICHED = "LEAD_ENRICHED"
LEAD_QUALIFIED = "LEAD_QUALIFIED"
LEAD_GHOSTED = "LEAD_GHOSTED"
LEAD_NURTURED = "LEAD_NURTURED"
LEAD_BLOCKED = "LEAD_BLOCKED"
LEAD_UNBLOCKED = "LEAD_UNBLOCKED"

# ── Sample events ──
SAMPLE_REQUESTED = "SAMPLE_REQUESTED"
LOT_CONFIRMED = "LOT_CONFIRMED"
LOT_CONFIRMATION_FAILED = "LOT_CONFIRMATION_FAILED"
SAMPLE_DISPATCHED = "SAMPLE_DISPATCHED"
SAMPLE_DELIVERED = "SAMPLE_DELIVERED"
CUPPING_SCORE_RECEIVED = "CUPPING_SCORE_RECEIVED"
SAMPLE_APPROVED = "SAMPLE_APPROVED"
SAMPLE_REJECTED = "SAMPLE_REJECTED"
SAMPLE_NEEDS_ANOTHER = "SAMPLE_NEEDS_ANOTHER"

# ── Contract events ──
CONTRACT_DRAFTED = "CONTRACT_DRAFTED"
CONTRACT_SIGNED = "CONTRACT_SIGNED"
CONTRACT_COMPLETED = "CONTRACT_COMPLETED"

# ── Logistics events ──
SHIPMENT_BOOKED = "SHIPMENT_BOOKED"
SHIPMENT_DEPARTED = "SHIPMENT_DEPARTED"
SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED"
CUSTOMS_HOLD = "CUSTOMS_HOLD"

# ── Inventory events ──
LOT_ADDED = "LOT_ADDED"
LOT_DEPLETED = "LOT_DEPLETED"
LOT_QA_FLAGGED = "LOT_QA_FLAGGED"
LOT_QA_RELEASED = "LOT_QA_RELEASED"
STOCK_CORRECTED = "STOCK_CORRECTED"

# ── Budget events ──
BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
BUDGET_RESET = "BUDGET_RESET"

# ── Relationship events ──
ACCOUNT_CREATED = "ACCOUNT_CREATED"
NPS_COLLECTED = "NPS_COLLECTED"
REPEAT_ORDER_REQUESTED = "REPEAT_ORDER_REQUESTED"

# ── System events ──
AGENT_STARTED = "AGENT_STARTED"
AGENT_COMPLETED = "AGENT_COMPLETED"
AGENT_FAILED = "AGENT_FAILED"
DAILY_SYNC_GENERATED = "DAILY_SYNC_GENERATED"

# ── Messaging Gateway events (Agent 3 + inbound webhook) ──
MESSAGE_SENT = "MESSAGE_SENT"
MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
MESSAGE_REPLIED = "MESSAGE_REPLIED"
MESSAGE_PROCESSED = "MESSAGE_PROCESSED"
THREAD_OPENED = "THREAD_OPENED"
THREAD_CLOSED = "THREAD_CLOSED"

# ── All event types (for validation) ──
ALL_EVENT_TYPES: frozenset[str] = frozenset(
    {
        # Lead
        LEAD_CREATED,
        LEAD_ENRICHED,
        LEAD_QUALIFIED,
        LEAD_GHOSTED,
        LEAD_NURTURED,
        LEAD_BLOCKED,
        LEAD_UNBLOCKED,
        # Sample
        SAMPLE_REQUESTED,
        LOT_CONFIRMED,
        LOT_CONFIRMATION_FAILED,
        SAMPLE_DISPATCHED,
        SAMPLE_DELIVERED,
        CUPPING_SCORE_RECEIVED,
        SAMPLE_APPROVED,
        SAMPLE_REJECTED,
        SAMPLE_NEEDS_ANOTHER,
        # Contract
        CONTRACT_DRAFTED,
        CONTRACT_SIGNED,
        CONTRACT_COMPLETED,
        # Logistics
        SHIPMENT_BOOKED,
        SHIPMENT_DEPARTED,
        SHIPMENT_DELIVERED,
        CUSTOMS_HOLD,
        # Inventory
        LOT_ADDED,
        LOT_DEPLETED,
        LOT_QA_FLAGGED,
        LOT_QA_RELEASED,
        STOCK_CORRECTED,
        # Budget
        BUDGET_EXHAUSTED,
        BUDGET_RESET,
        # Relationship
        ACCOUNT_CREATED,
        NPS_COLLECTED,
        REPEAT_ORDER_REQUESTED,
        # System
        AGENT_STARTED,
        AGENT_COMPLETED,
        AGENT_FAILED,
        DAILY_SYNC_GENERATED,
        # Messaging Gateway
        MESSAGE_SENT,
        MESSAGE_RECEIVED,
        MESSAGE_REPLIED,
        MESSAGE_PROCESSED,
        THREAD_OPENED,
        THREAD_CLOSED,
    }
)
